# Generated by Django 5.1.3 on 2024-12-04 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_acao', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investimento', models.FloatField()),
                ('data_prevista', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('tipo_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamento.tipoacao')),
            ],
        ),
    ]
