# Generated by Django 5.1.3 on 2024-12-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0003_alter_acao_investimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='investimento',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
